config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'calendar',                to: 'calendar#index'
  get 'contribute',              to: 'contribute#index'
  get 'irc',                     to: 'irc#index'
  get 'newsletter',              to: 'newsletter#index'
  get 'newsletter/:campaign_id', to: 'newsletter#get_campaign'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocIT</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'favicon' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <%# Menu button for mobile devices %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <%# The three bars in the menu button %>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!-- Tag the navbar with an environment label -->
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag 'socit.png', id: 'socit-logo' %>
        <% unless Rails.env.production? %>
          <span class="label label-success"><%= Rails.env %></span>
        <% end %>
      <% end %>
    </div>

    <%# Navbar left align %>
    <div class="collapse navbar-collapse" id="navbar-main-collapse">

      <%# See: app/helpers/application_helper.rb %>
      <%= nav_bar do %>
        <%= nav_link "News",            newsletter_path %>
        <%= nav_link "Events Calendar", calendar_path %>
        <%= nav_link "IRC",             irc_path %>
        <%= nav_link "Contribute",      contribute_path %>
      <% end %>

      <%# Navbar right align %>
      <ul class="nav navbar-nav navbar-right nav-pills">
        <%# <% if user_signed_in? %>
        <%#   <li><%= link_to current_user.name %></li>
        <%#   <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <%# <% else %>
        <%#   <li class="active"><%= link_to "Sign Up", new_user_registration_path %></li>
        <%#   <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
        <%#   <li><%= link_to('Login', new_user_session_path)  %></li>
        <%# <% end %>
      </ul>
    </div>
</nav>

<div class="container">
  <% if notice %>
    <%= bootstrap_alert :success do %>
      <%= notice %></p>
    <% end %>
  <% end %>

  <% if alert %>
    <%= bootstrap_alert :danger do %>
      <%= alert %>
    <% end %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>